### PR TITLE
fix: fix diff functionality

### PR DESCRIPTION
**Pull request by cameronklein**
## Description

Reverts to the original diff functionality

Issue: https://github.com/invertase/melos/issues/557

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Comment by cameronklein** [comment]
Thanks! I signed the agreement but it doesn't seem to be updating. I've clicked the `recheck` link a few times but no luck. It's also not letting me sign it again.

Screenshot 2023-08-11 at 1 10 27 PM

**Comment by Him-Sharma** [comment]
Thanks for fixing this. Do you know when can we merge this? this is impacting our workflows as well.

**Comment by Salakar** [comment]
Is there any implications on reversing this? I understand the original change was done mainly for cleanup but not sure the reasoning of switching the diff logic.

Maybe there is there an interim way we can support both for now that way we ship it faster and worry about reversal implications later?

**Comment by spydon** [comment]
@cameronklein did you see the questions from Salakar? :)

**Comment by cameronklein** [comment]
It does make sense to support both but I personally don't have the bandwidth. We've forked the repo and made the change for our use case. I'll keep the issue (https://github.com/invertase/melos/issues/557) open for anyone that does have more time!

**Comment by spydon** [comment]
> It does make sense to support both but I personally don't have the bandwidth. We've forked the repo and made the change for our use case. I'll keep the issue (https://github.com/invertase/melos/issues/557) open for anyone that does have more time!

Maybe it is worth opening up and merging this anyways, is there any usecase for supporting both? Isn't this way just "more correct"?

**Comment by xsahil03x** [comment]
Yes, I agree. @cameron-klein can you please re-open this PR and we can hopefully get it merged this time? Thanks

**Comment by spydon** [comment]
It would be great to have your input here @blaugold, because I don't fully get it there would be any downsides.

**Comment by xsahil03x** [comment]
Hey @blaugold can you please take a look at this today? Thanks

**Comment by xsahil03x** [comment]
Hey @spydon, what do you suggest we should do next?

**Comment by spydon** [comment]
> Hey @spydon, what do you suggest we should do next?

Could you open up a new PR with the only  changes that are needed from this PR and I could get some other people to review it too? And I'll do some more research on what these changes would entail, so that I can review it better.

**Comment by blaugold** [comment]
Sorry for the delay. I'm taking a look at it now.

**Comment by blaugold** [comment]
If I remember correctly, I moved from `git diff` to `git log` for detecting changes in a package only for simplifying things and not for any functionality. 

These changes look to me like they only improve the correctness of `--diff` and I can't see any functionality being taken away. I think it makes sense to merge this PR.

**Pull request closed without merging**
