### PR TITLE
docs: Add signals to list of projects using Melos

### PR DESCRIPTION
**Pull request by rodydavis**
## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [ ] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Comment by spydon** [comment]
Thanks for the submission @rodydavis, can you please sign the CLA by following the link above? :)

**Comment by rodydavis** [comment]
I signed the CLA, but not sure why it is rechecking!

**Comment by rodydavis** [comment]
Anything else I need to do?

**Comment by spydon** [comment]
> Anything else I need to do?

It's all good, it's just a flaky test that needs to pass

**Pull request merged**
