### PR TITLE
fix: Use text script rather than fixed script paths

### PR DESCRIPTION
**Pull request by AlexV525**
## Description

The `melos` executable path could be changed due to environment updates. Using a text script and letting the configuration run in the terminal can reduce the pain of checking out these configurations into version control.

## Type of Change

- [x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Comment by AlexV525** [comment]
@spydon Thanks for the approve. I have little time to improve this with some potential tests. If you think it's fine then I will mark this as ready.

**Comment by spydon** [comment]
> @spydon Thanks for the approve. I have little time to improve this with some potential tests. If you think it's fine then I will mark this as ready.

I think it's fine, it looks like it makes sense and I assume you've tested it manually.

**Review by spydon — APPROVED** [review]

**Comment by AlexV525** [comment]
Hi @spydon. I'm still seeing the old style of generated configurations. I saw the commit was published in v6.3.2 and I was using the exact same version. Is there something missing from the publish?

**Comment by spydon** [comment]
Hey @AlexV525, everything should be out.
Maybe something went wrong with this PR so that it didn't have any effect then? 🤔

**Comment by spydon** [comment]
Have you tried if it works on the 7.0.0 pre-releasd version?

**Comment by AlexV525** [comment]
I just upgraded my workspace dependency and it seems working. I used to think that a globally activated package would ignore the resolved version in the workspace, but now it appears not.

**Pull request merged**
