### PR TITLE
docs: link Melos logo in README

### PR DESCRIPTION
**Pull request by Abubakrce19**
Resloved #414 
## Type of Change

- [ ] ✨ `feat` -- This includes hyperlinking the melos logo with thier website in readme.md file.
- [ ] 🛠️ `fix` --
- [ ] ❌ `!` -- 
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [x] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Comment by Abubakrce19** [comment]
@ryanhanks 
@shyndman 
@jpnurmi

**Comment by Abubakrce19** [comment]
@blaugold 
Please have a look
Thank you

**Comment by Abubakrce19** [comment]
@blaugold 
Please add "hactoberfest-accepted" label .
So I could be counted for Invertase swags.
Thank you soo much

**Comment by blaugold** [comment]
Please see the [guidelines](https://invertase.io/community/hacktoberfest) for what types of PRs qualify for Hacktoberfest. This PR does not meet those requirements.

**Comment by Abubakrce19** [comment]
> Please see the [guidelines](https://invertase.io/community/hacktoberfest) for what types of PRs qualify for Hacktoberfest. This PR does not meet those requirements.

Will docs improvement (typo and grammer) 
Be counted?

**Comment by blaugold** [comment]
Sorry, I linked the wrong URL. Here is the correct link for the [guidelines](https://archive.invertase.io/community/hacktoberfest).

Those types of contributions are not counted.

**Pull request merged**
