### PR TITLE
feat: VSCode workspace generator script

### PR DESCRIPTION
**Pull request by KieranLafferty**
I wrote this script package a while back which generates a VSCode project file out of the dependency tree reported by melos. I've found it pretty useful for larger projects that overwhelm the dart analyzer when too many folders (often unused ones) are open at the same time

Thought I would put this up and see if there's any interest in having such a script in this repo. No worries at all if it's not a good fit. 

If there is interest I can spend some time to clean it up a bit and make any changes requested.

Thank you to all who contribute to Melos 🙌

### CODE REVIEW

**Comment by blaugold** [comment]
Hey @KieranLafferty, I'm the maintainer of the [VS Code extension](https://github.com/blaugold/melos-code) for Melos. This looks like a feature that might be better implemented there.

**Comment by Salakar** [comment]
> Hey @KieranLafferty, I'm the maintainer of the [VS Code extension](https://github.com/blaugold/melos-code) for Melos. This looks like a feature that might be better implemented there.

This would be good, is there perhaps a VS Code Extension API/way of doing this (defining projects) without generating a file?

**Comment by blaugold** [comment]
We could have a command that when executed:
- asks for a package, 
- generates a workspace config which contains workspace folders for the package and its dependents,
- writes that file to a temporary location,
- opens a new VS Code windows with that workspace config.

**Comment by KieranLafferty** [comment]
Apologies for the late response here   @blaugold  @Salakar

Happy to move it over to that VSCode extension. Want me to close this and create a PR there and we can discuss how it integrates on the new PR?

**Comment by blaugold** [comment]
@KieranLafferty No problem :)

I've opened a new issue in extension repo (https://github.com/blaugold/melos-code/issues/26), with some thoughts I had. Let's discuss what this feature should do and how to implement it.

**Comment by KieranLafferty** [comment]
Closing this to continue the convo on the other task

**Pull request closed without merging**
