### PR TITLE
feat: Add topological sort to publish command

### PR DESCRIPTION
**Pull request by dnys1**
Fixes https://github.com/invertase/melos/issues/149

Adds topological sorting to the `publish` command so that packages may be published in order based on their dependencies on other workspace packages.

### CODE REVIEW

**Comment by Ehesp** [comment]
Thanks for this. The team is pretty busy right now but we'll get this reviewed ASAP.

**Comment by Salakar** [comment]
Thanks for this, I've taken a look already and it looks great. My only concern is having a `CycleException` being thrown is a breaking changing, some repositories have cyclic dependencies, e.g. FlutterFire - so this will break publishing. Is there any way to sort what we can and any that can't be sorted due to cyclic dependencies just bump them to the top/bottom of the ordering?

**Comment by dnys1** [comment]
Thanks, @Salakar! I think the best we can do in that case is to leave packages with inter-dependencies untouched, since they cannot be topologically sorted. I've updated the code to, in essence, ignore cyclic errors. Let me know how that sounds.

Anything more complicated such as sorting a subgraph of packages which do not have inter-dependencies is possible - although I'm not sure how worthwhile the investment would be. Let me know!

**Comment by Salakar** [comment]
> Thanks, @Salakar! I think the best we can do in that case is to leave packages with inter-dependencies untouched, since they cannot be topologically sorted. I've updated the code to, in essence, ignore cyclic errors. Let me know how that sounds.
> 
> Anything more complicated such as sorting a subgraph of packages which do not have inter-dependencies is possible - although I'm not sure how worthwhile the investment would be. Let me know!

This is perfect for now, thanks for addressing review points

**Comment by dnys1** [comment]
Awesome - thanks @Salakar!

**Pull request merged**
