### PR TITLE
feat: follow symlinks when resolving packages

### PR DESCRIPTION
**Pull request by Quijx**
This PR makes it so that projects are found if they are reachable through paths containing links that are allowed in the `melos.yaml`.

This change is roughly implemented as discussed here: https://github.com/invertase/melos/issues/43#issuecomment-746203744

A few notes:
- I have added a check that the found `FileSystemEntity` is a `File`. That should stop problems with folders named `pubspec.yaml` (Even if likely nobody ever would do this. :smile:)
- I used the `basename` function from the `path` package instead of `file.path.endsWith('pubspec.yaml')` to check if the file is named `pubspec.yaml` to avoid problems with files called for example `old_pubspec.yaml`
- I could not use `.toSet()` as you suggested in https://github.com/invertase/melos/issues/43#issuecomment-746203744 because `File` does not override `==` such that they are equal if they point to the same file.
- If a `pubspec.yaml` is reachable through one or more links and directly, either path could be added to `allPubspecs`. I assumed it is not important which one is taken. Is that assumption correct, or should i add a check to use the direct path if it is available?
- I have not thought through any implications this change might have because projects outside of the project root are now allowed. I am not familiar enough with the inner workings of melos, so I'll let you think that through :smile:

### CODE REVIEW

**Comment by Quijx** [comment]
So I have another idea about how to find the files matching the globs in `packages`: Instead of listing the contents of the workspace directory and filtering the ones matching the globs, one could use the `listFileSystem` function on the globs themselves. That could be faster in some cases because only paths need to be followed that even have the chance of matching the glob. However some paths might be visited multiple times if the globs overlap. This would also have the implication that paths outside the root can be added as packages, for example with the glob `../outside_package/*`. Is that something you would want? Should be easy to implement.

**Comment by Quijx** [comment]
So I fixed the lints that caused the `analyze` job to fail, but I'm not so sure why the `test_macos` job (https://github.com/invertase/melos/runs/4505402142?check_suite_focus=true) failed. Locally the test `test/commands/bootstrap_test.dart: bootstrap resolves workspace packages with path dependency` passes for me and sadly I don't have a macos computer to test it. I could use some help here...

**Review by Salakar — APPROVED** [review]

**Comment by Salakar** [comment]
I think this is ok to go in it's current form, unless you have any reason it should not be merged yet?

I also want to test it out on FlutterFire manually to make sure all is well

**Comment by Quijx** [comment]
I think it's fine in its current form. If you think there will be performance problems because some people might link large parts of the file system that have to be searched on every bootstrap, I can look into the `glob.listFileSystem` solution. But i expect most people will only link the project folders, so it's probably fine. So you can merge if you want.

**Review by Salakar — APPROVED** [review]

**Pull request merged**
