### PR TITLE
fix: resolve to correct diff revisionRange

### PR DESCRIPTION
**Pull request by xsahil03x**
## Description
Fixes: #673

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Lgtm

**Comment by xsahil03x** [comment]
Hey @spydon , can we merge this PR?

**Comment by xsahil03x** [comment]
@spydon when can we expect this in release?

**Comment by xsahil03x** [comment]
Hey @spydon,any update?

**Comment by spydon** [comment]
> Hey @spydon,any update?

Hi, we don't do releases after every merge, but it'll probably be released some time during the week.

**Comment by xsahil03x** [comment]
Thanks, waiting for it as the diff fix released earlier isn't really working without this.

**Comment by spydon** [comment]
> Thanks, waiting for it as the diff fix released earlier isn't really working without this.

You can use it directly from git meanwhile:
```
dart pub global activate https://github.com/invertase/melos.git --git-path packages/melos --source git
```

**Pull request merged**
