### PR TITLE
chore(melos): updated dependencies to latest stable versions

### PR DESCRIPTION
**Pull request by OutdatedGuy**
## Description

Updated packages [file](https://pub.dev/packages/file) and [pub_updater](https://pub.dev/packages/pub_updater) to latest stable versions i.e. `v7.0.0` and `v0.4.0` respectively.

Also updated dependency versions in the `melos.yaml` file to properly bootstrap melos while using `melos bootstrap`.

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [ ] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [x] 🗑️ `chore` -- Chore

### CODE REVIEW

**Review by spydon — CHANGES_REQUESTED** [review]
This does not pass the version constraints.

**Review by spydon — COMMENTED** [review]
I don't think this change gives us anything, it will be more work maintaining those dependency ranges. It's better to wait with bumping these dependencies until we bump Dart.

**Comment by OutdatedGuy** [comment]
Yo @spydon, this is the same tactic we used while updating the `http` package in [this commit](https://github.com/invertase/melos/commit/979d0b157b4cffa4d91882be3a3a5be03dcbd147).

Also because of these constraints, I'm unable to add melos as I'm using packages with the latest versions of `pub_updater` and `file`.

Additionally, we can later remove the range after the current melos is updated.

**Comment by spydon** [comment]
> Yo @spydon, this is the same tactic we used while updating the `http` package in [this commit](https://github.com/invertase/melos/commit/979d0b157b4cffa4d91882be3a3a5be03dcbd147).
> 
> Also because of these constraints, I'm unable to add melos as I'm using packages with the latest versions of `pub_updater` and `file`.
> 
> Additionally, we can later remove the range after the current melos is updated.

The dependencies of Melos should not affect your usage of it? If you have a package/app in the root I recommend that you move it into a sub-directory, for example `packages/` for packages or `apps/` for apps, because you shouldn't share the Melos workspace pubspec.

**Pull request closed without merging**
