### PR TITLE
fix: multiline run commands were failing

### PR DESCRIPTION
**Pull request by pastre**
## Description

Multiline scripts were not properly being parsed in order to run. Trimming them before creation ensures no empty spaces interfere with the script's execution

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [X] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Comment by spydon** [comment]
Can you give an example of a script that would fail? All our multi-line scripts work as intended as far as I know.
I think this might even break some scripts, since it would remove the newline characters and if people have escaped the newline with a backslash it would create a trailing `\` that wouldn't escape the right thing.

On another note, most of the time the new `steps` feature can be used instead of multi-line scripts:
https://melos.invertase.dev/configuration/scripts#steps

**Comment by pastre** [comment]
@spydon  Sorry, I could've been a little more descriptive on the bug - and also thanks for the quick feedback!
The bug happens when passing additional arguments to a multiline YAML string - it apparently takes those arguments in as new commands and attempts to execute them
With this script:
```
scripts:
  build:
    run: |
      echo $1 $2 $3
```

I got the following output
```
$ melos build with extra arguments
melos run build
  └> echo $1 $2 $3
      with extra arguments
     └> RUNNING


ERROR: /bin/sh: line 1: with: command not found


melos run build
  └> echo $1 $2 $3
      with extra arguments
     └> FAILED
ScriptException: The script build failed to execute.
```

**Comment by spydon** [comment]
@pastre ah, I see, that is filed as bug #232, and there is a good description about why these types of scripts are problematic [here](https://github.com/invertase/melos/issues/232#issuecomment-1619656025).

**Comment by spydon** [comment]
I'll close this meanwhile, since this fix will break other scripts. We can continue the discussion in the issue instead.

**Comment by pastre** [comment]
Cool, thanks for pointing towards the right direction @spydon :)

**Pull request closed without merging**
