### PR TITLE
feat: Change concurrent log to sequential log

### PR DESCRIPTION
**Pull request by koji-1009**
## Description

issue #668 

Improvements `melos analyse` log so that the output is the same when the `-c` option is specified as when it is not specified.
The `String? group` property is added for grouping when logging output. In the case of `-c 1`, this option is not needed. (Log output is done sequentially.) In the case of `-c 2`, all logs are output after the process is complete.

Existing buffer-flush was deprecated, so it was named group-buffer for convenience. If that is not good, please point it out. Thanks for the useful tools.

### no issue case

<details open><summary>main branch log</summary>

```console
# koji @ Mochi in ~/packages/melos on git:main o [19:03:18]
$ melos analyze -c 1
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze
     └> RUNNING (in 3 packages)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
conventional_commit:
Analyzing conventional_commit...
No issues found!
conventional_commit: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos:
Analyzing melos...
No issues found!
melos: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos_workspace:
Analyzing melos...
No issues found!
melos_workspace: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze
     └> SUCCESS

# koji @ Mochi in ~/packages/melos on git:main o [19:03:24]
$ melos analyze -c 2
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze --concurrency 2
     └> RUNNING (in 3 packages)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Analyzing conventional_commit...
Analyzing melos...
No issues found!
No issues found!
Analyzing melos...
No issues found!
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze --concurrency 2
     └> SUCCESS
```

</details>

<details open><summary>this branch log</summary>

```console
# koji @ Mochi in ~/packages/melos on git:feat/concurrent_log o [19:05:11]
$ melos analyze -c 1
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze
     └> RUNNING (in 3 packages)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
conventional_commit:
Analyzing conventional_commit...
No issues found!
conventional_commit: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos:
Analyzing melos...
No issues found!
melos: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos_workspace:
Analyzing melos...
No issues found!
melos_workspace: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze
     └> SUCCESS

# koji @ Mochi in ~/packages/melos on git:feat/concurrent_log o [19:05:18]
$ melos analyze -c 2
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze --concurrency 2
     └> RUNNING (in 3 packages)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
conventional_commit:
Analyzing conventional_commit...
No issues found!
conventional_commit: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos:
Analyzing melos...
No issues found!
melos: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos_workspace:
Analyzing melos...
No issues found!
melos_workspace: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze --concurrency 2
     └> SUCCESS
```

</details>

## find issue case

<details open><summary>main branch log</summary>

```console
# koji @ Mochi in ~/packages/melos on git:main o [19:12:36]
$ melos analyze -c 1
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze
     └> RUNNING (in 3 packages)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
conventional_commit:
Analyzing conventional_commit...
No issues found!
conventional_commit: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos:
Analyzing melos...

   info - lib/src/commands/analyze.dart:30:4 - Missing a required trailing comma. - require_trailing_commas

1 issue found.
melos: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos_workspace:
Analyzing melos...

   info - packages/melos/lib/src/commands/analyze.dart:30:4 - Missing a required trailing comma. - require_trailing_commas

1 issue found.
melos_workspace: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze
     └> SUCCESS

# koji @ Mochi in ~/packages/melos on git:main x [19:12:51]
$ melos analyze -c 2
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze --concurrency 2
     └> RUNNING (in 3 packages)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Analyzing conventional_commit...
Analyzing melos...
No issues found!

   info - lib/src/commands/analyze.dart:30:4 - Missing a required trailing comma. - require_trailing_commas

1 issue found.
Analyzing melos...

   info - packages/melos/lib/src/commands/analyze.dart:30:4 - Missing a required trailing comma. - require_trailing_commas

1 issue found.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze --concurrency 2
     └> SUCCESS
```

</details>

<details open><summary>this branch log</summary>

```console
# koji @ Mochi in ~/packages/melos on git:feat/concurrent_log x [19:14:58]
$ melos analyze -c 1
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze
     └> RUNNING (in 3 packages)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
conventional_commit:
Analyzing conventional_commit...
No issues found!
conventional_commit: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos:
Analyzing melos...

   info - lib/src/commands/analyze.dart:30:4 - Missing a required trailing comma. - require_trailing_commas

1 issue found.
melos: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos_workspace:
Analyzing melos...

   info - packages/melos/lib/src/commands/analyze.dart:30:4 - Missing a required trailing comma. - require_trailing_commas

1 issue found.
melos_workspace: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze
     └> SUCCESS

# koji @ Mochi in ~/packages/melos on git:feat/concurrent_log x [19:15:07]
$ melos analyze -c 2
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze --concurrency 2
     └> RUNNING (in 3 packages)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
conventional_commit:
Analyzing conventional_commit...
No issues found!
conventional_commit: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos:
Analyzing melos...

   info - lib/src/commands/analyze.dart:30:4 - Missing a required trailing comma. - require_trailing_commas

1 issue found.
melos: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
melos_workspace:
Analyzing melos...

   info - packages/melos/lib/src/commands/analyze.dart:30:4 - Missing a required trailing comma. - require_trailing_commas

1 issue found.
melos_workspace: SUCCESS
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze --concurrency 2
     └> SUCCESS
```

</details>

## Type of Change

- [x] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [ ] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Review by spydon — COMMENTED** [review]
Thanks for your contribution, it looks good!
Could you just add a simple test?

**Comment by koji-1009** [comment]
Sure, I'll give it a try!

**Comment by spydon** [comment]
@koji-1009 there seems to be a test failing in this PR

**Comment by koji-1009** [comment]
I'm sorry! I had unintentionally changed the label flag to `true` when I changed it from `logger.stderr` to `logger.error`.

**Review by spydon — APPROVED** [review]
Lgtm, thanks for your contribution!

**Pull request merged**
