### PR TITLE
feat: Add `--yes` flag to `melos version` for ci support.

### PR DESCRIPTION
**Pull request by cyanglaz**
The version command requires a prompt which blocks it to be run on CI.
This PR adds a `yes` flag so the prompt can be skipped.

This also fixed a format issue.

### CODE REVIEW

**Comment by cyanglaz** [comment]
Line 249 has something like 
```
await MelosCommandRunner.instance.run(['run', 'version']);
```

This seems to run the same command twice, is it intentional?

**Review by Salakar — APPROVED** [review]
LGTM - thanks for this, will sort CI issue separately and then get this merged & released

**Comment by Salakar** [comment]
> Line 249 has something like
> 
> ```
> await MelosCommandRunner.instance.run(['run', 'version']);
> ```
> 
> This seems to run the same command twice, is it intentional?
> 
> cc @Salakar

This is running the the named script defined in the `melos.yaml` thats named `version`, not the same as `melos version`, it's the equivalent of `melos run version` (it's for running a custom script/step pre/post versioning happening).

**Comment by cyanglaz** [comment]
@Salakar Ah, that makes sense, thanks!

**Pull request merged**
