### PR TITLE
feat: add "--no-example" arg to "pub get " command for melos bootstrap

### PR DESCRIPTION
**Pull request by ankiimation**
## Description

- add ``` --no-example ``` arg for ```dart/flutter pub get``` of bootstrap command [https://github.com/dart-lang/pub/pull/3856](url)

## Usage
```
melos bs --no-example
```

## Type of Change

- [ x] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [ ] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Review by spydon — COMMENTED** [review]
Looks sensible, missing docs and tests though.

**Comment by ankiimation** [comment]
updated relative url

**Comment by spydon** [comment]
@ankiimation could you add some docs to https://github.com/invertase/melos/blob/main/docs/commands/bootstrap.mdx and then we can merge this? :)

**Comment by ankiimation** [comment]
> @ankiimation could you add some docs to https://github.com/invertase/melos/blob/main/docs/commands/bootstrap.mdx and then we can merge this? :)

udpated 💪

**Review by spydon — APPROVED** [review]

**Pull request merged**
