### PR TITLE
fix: support external hosted dependencies

### PR DESCRIPTION
**Pull request by ekasetiawans**
## Description

When we call `melos version` the package's pubspec.yaml should be updated to the latest dependency version. But, currently not works if the package is hosted in external hosted (self hosted pub).

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Comment by Salakar** [comment]
Could you give me an example of what a pubspec.yaml looks like with external hosted dependency version? Thanks

**Comment by ekasetiawans** [comment]
@Salakar here is my pubspec.yaml with external hosted dependency

```
name: xetia_purchase
description: A new flutter plugin project.
version: 1.5.0
homepage: https://xetia.io
repository: https://github.com/jsc-app-2020/XETIA-Monorepo.git
publish_to: https://pub.xetia.dev

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  xetia_core:
    hosted:
      name: xetia_core
      url: https://pub.xetia.dev
    version: ^1.12.0

  xetia_chat_interface:
    hosted:
      name: xetia_chat_interface
      url: https://pub.xetia.dev
    version: ^1.1.0

  xetia_widgets:
    hosted:
      name: xetia_widgets
      url: https://pub.xetia.dev
    version: ^1.5.0

  google_maps_flutter: ^2.1.1
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  geolocator: ^8.2.0
  intl: ^0.17.0
  pdf: ^3.7.1
  printing: ^5.7.2
  flutter_bluetooth_printer: ^1.1.10
  rive: ^0.8.1
  shared_preferences: ^2.0.13
  flutter_stripe: ^2.2.0
  in_app_purchase: ^3.0.0
  in_app_purchase_storekit: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  # plugin:
  #   platforms:
  #   # This plugin project was generated without specifying any
  #   # platforms with the `--platform` argument. If you see the `some_platform` map below, remove it and
  #   # then add platforms following the instruction here:
  #   # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
  #   # -------------------
  #     some_platform:
  #       pluginClass: somePluginClass
  #   # -------------------

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/illustration/
    - assets/rive/
    - assets/svg/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

languages:
  - en
  - id
  - ja
  - ar
  - zh_CN
  - ko
  - ru
```

Note that: currently we have an issue to the https://pub.dev/packages/pubspec package which can't read pubspec.yaml when contains external hosted dependency. But, we can temporarily using this PR https://github.com/j4qfrost/pubspec/pull/4 to solve that.

**Comment by ekasetiawans** [comment]
Here is also reference for external hosted dependency https://dart.dev/tools/pub/dependencies#hosted-packages

**Comment by ekasetiawans** [comment]
@Salakar I have push some update and fix conflicts, could you review it?
The pubspec package issue about external hosted dependencies is now fixed in pubspec: 2.1.0 and I have update it too.

**Comment by Salakar** [comment]
Hey @ekasetiawans, I'#ve pushed a change to switch to using a regex, which is more explicit and also supports `any` or null versions, can see an example of the regex working here: https://regex101.com/r/ob8xRv/1

**Comment by ekasetiawans** [comment]
@Salakar thank you

**Comment by ekasetiawans** [comment]
I have created another PR #262

**Pull request merged**
