### PR TITLE
feat: Add global dependency overrides

### PR DESCRIPTION
**Pull request by jtdLab**
## Description

Support global dependency_overrides (#439)

This allows to define dependency overrides for each workspace package in `melos.yaml` like:

```yaml
name: foo

packages:
  - packages/**

globalDependencyOverrides:
  my_dependency: 1.2.3
```

## Type of Change

- [x] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [ ] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

### CODE REVIEW

**Comment by jtdLab** [comment]
Hint:

The added `globalDependencyOverrides` and the existing [dependencyOverridePaths](https://melos.invertase.dev/configuration/overview#dependencyoverridepaths) do add the dependency override to all workspace packages. This means packages that do not have a regular or dev dependency also get the override which seems to be bad. Is this behaviour intended?

**Comment by blaugold** [comment]
@jtdLab Thanks for this contribution!

We already have [`dependencyOverridePaths `](https://melos.invertase.dev/configuration/overview#dependencyoverridepaths). Could you make the new option a sibling of that one? I think `dependencyOverrides` would be enough as its name. Please also document the new option.

> Is this behaviour intended?

Yes. Often, dependency overrides are used to override transitive dependencies.

**Comment by jtdLab** [comment]
@blaugold i am no sure about the docs is it only the overview page which needs an update?

**Comment by jtdLab** [comment]
> Yes. Often, dependency overrides are used to override transitive dependencies.

Does this lead to problems when a non-flutter workspace package receives a transitive dependency on a flutter package?

**Comment by jtdLab** [comment]
Any updates on this?

**Comment by spydon** [comment]
@jtdLab this is offering the same functionality as #594 right?

**Comment by spydon** [comment]
I'll close this since the functionality will be implemented with the new system in 594, thanks for the effort though!

**Pull request closed without merging**
